@Library('mylibrary')_
pipeline
{
    agent any
    stages
    {
        stage('continuousdownload')
        {
            steps
            {
                script
                {
                    cicd.gitdownload("maven")
                }
            }
        }
        stage('continuousbuild')
        {
            steps
            {
                script
                {
                    cicd.mavenbuild()
                }
            }
        }
        stage('continuousdeployment')
        {
            steps
            {
                script
                {
                    cicd.tomcatdeploy("declarativepipelinesharedlibrary1","172.31.18.57","testap")
                }
            }
        }
        stage('continuoustesting')
        {
            steps
            {
                script
                {
                    cicd.gitdownload("FunctionalTesting")
                    cicd.runselenium("declarativepipelinesharedlibrary1")
                }
            }
        }
        stage('continuousdelivery')
        {
            steps
            {
                script
                {
                    cicd.tomcatdeploy("declarativepipelinesharedlibrary1","172.31.24.82","pordap")
                }
            }
        }
    }
}
